spring:
  application:
    name: greeting-service
management:  endpoints:    web:      exposure:        include:        - '*'
greeting-service:
  greeting: "Hello PERF"
  default-value: "Mundo"